server:
  port: 2003

spring:
  application:
    name: account-service
  cloud:
    alibaba:
      seata:
        tx-service-group: my_tx_group #自定义事务组名称需要与seata-server中的对应
    nacos:
      discovery:
        server-addr: 192.168.17.102:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.17.102:3306/seata_account
    username: root
    password: 123456

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml